server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/schooldriva}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:otaku}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:test@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:test}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:schooldriva_secret_key_2026_very_long_string_at_least_256_bits_ok}
    expiration: ${APP_JWT_EXPIRATION:86400000}
  upload:
    dossier: ${APP_UPLOAD_DOSSIER:/home/otaku/school-driva-uploads/documents}